# Generated by Django 4.0.8 on 2022-10-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalbase',
            name='account',
        ),
        migrations.RemoveField(
            model_name='recoverbase',
            name='account',
        ),
        migrations.AddField(
            model_name='finalbase',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
