# Generated by Django 4.0.8 on 2022-10-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basses', '0002_remove_finalbase_account_remove_recoverbase_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalbase',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
