# Generated by Django 4.0.8 on 2022-10-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basses', '0003_alter_finalbase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalbase',
            name='newGestor',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='recoverbase',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
