# Generated by Django 4.0.8 on 2022-10-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basses', '0005_alter_recoverbase_numberone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalbase',
            name='document',
            field=models.CharField(default='document', max_length=255),
        ),
        migrations.AlterField(
            model_name='finalbase',
            name='numberOne',
            field=models.CharField(default='number', max_length=255),
        ),
        migrations.AlterField(
            model_name='finalbase',
            name='numberTwo',
            field=models.CharField(default='number', max_length=255),
        ),
        migrations.AlterField(
            model_name='recoverbase',
            name='document',
            field=models.CharField(default='document', max_length=255),
        ),
    ]
